### ISSUE TITLE
'NA' instances in test set

### ISSUE THREAD

**Issue by nayakt** [Spico197/NYT-H#2]
Do you include any 'NA' instances in the evaluation ? Or do you consider the 'No' annotations of non-NA DS sentences as 'NA' during evaluation ?

**Comment by Spico197** [comment]
Thanks for your questions.

1. No NA instances are in the evaluation sets.
2. During evaluation, the `NO` annotations cannot be fully utilized, depending on different conditions. If one instance (DS-labelled as `r`) is annotated as `NO` in the test set, then it can be any other relations except relation `r` itself, which means the ground truth can be NA or other non-NA relations. Under this situation, whether this instance can be used for evaluation depends on the prediction result. If it's predicted as relation `r`, then we can know that the prediction is wrong. If it's predicted as other relations, then we cannot evaluate it in this situation, so this predicition will not be considerated during evaluation. In addition, that's why the `K` value in the final P@K measures cannot exceed the number of `Yes` instances in the test  set.

For a more straightforward understanding of the evaluation process, I made the figure below. Each prediction is in a binary format. The green boxes mean the DS-labelled relations, and the red right and wrong symbols mean the manually-annotated results. For each relation, there are corresponding available 0-1 prediction and answer sequences, so we can calculate the final F1 scores for each relation, together with the final macro-averaged F1 scores.
![image](https://user-images.githubusercontent.com/22840952/99218350-38f5f700-2815-11eb-9a34-6a0b5ad1b63f.png)

If you have any further questions, please keep in touch.

**Comment by nttmac** [comment]
Hello, thanks for your great work!
I am confused that there are NA sentences during training while no NA instances are in the evaluation sets. I think training and testing should be consistent and it's better to consider NA instances during evaluating.

**Comment by Spico197** [comment]
> Hello, thanks for your great work!
> I am confused that there are NA sentences during training while no NA instances are in the evaluation sets. I think training and testing should be consistent and it's better to consider NA instances during evaluating.

Here, we follow the tradition of distantly-supervised relation extraction, and keep the evaluation set out of NA distractions. NA relation is worth trying to dig into, where most the False Negative noises are mixed. NA is probabily helpful to offer a boundary of other non-NA relations ideally, but sometimes it's hard to make full use of such information. FewShot2.0 considers NA as a new challenge, while former studies mainly focus on how to reduce the noise from NA. If you're interested in how to reduce the noise effect, you can check the Multi-Instance Learning methods, or Reinforcement Learning to select "purer" instances, and Positive-Unlabeled (PU) Learninig is also a good way to reduce the false negative noises (basically the NA effects).

Hope the comments above may solve your questions, and feel free to open a new issue if you have any further questions.
