### ISSUE TITLE
Entity Linking and GUID

### ISSUE THREAD

**Issue by rivercold** [Spico197/NYT-H#9]
Hi there,

Thank you for this interesting work. I am not able to find details in the paper about how entity linking was done. I am wondering what is the GUID in your data, and what are its connections with the mid in freebase (also in THU's released NYT version)? 

It would be great if you can also upload the pre-processing codes. 

Thank you!

**Comment by Spico197** [comment]
The original NYT10 dataset is at [here](http://iesl.cs.umass.edu/riedel/ecml/). There is an entity list with GUIDs , which I believe, are the GUIDs in the Freebase.

For preprocessing codes, you can follow the THU's released version [here](https://github.com/thunlp/OpenNRE/tree/old_version#installation).

Data file description:
- for entity GUID, entity text, and types: 
  - `filtered-freebase-simple-topic-dump-3cols.tsv`
  - `trainEntities.pb`
  - `testNewEntities.pb`
- for triples
  - `kb_manual/trainPositive.pb`
  - `kb_manual/trainNegative.pb`
  - `heldout_relations/trainPositive.pb`
  - `heldout_relations/trainNegative.pb`
  - `heldout_relations/testPositive.pb`
  - `heldout_relations/testNegative.pb`

**Comment by rivercold** [comment]
Thank you for the timely response! My take is that your dataset adopted the NER and entity linking results by Riedel et al. 2010?  

I am not so sure about the difference between folder "kb_manual" and "heldout_relations". Why are there trainPositive.pb and trainNegative.pb in the held out (maybe it is the naming issue)? Did you covert all "train*.pd" files in both folders?

Besides, I find there are some entity pairs that exist both in training (train_nonna.json) and testing (test.json), e.g., 
(chicago, field_museum_of_natural_history)  and (coney_island, new_york_city). Do you think we should probably remove them from either training or testing, in order to avoid the model remembering entities' relations as a shortcut?

**Comment by Spico197** [comment]
1. Yes.
2. Me neither. There're no official descriptions and instructions for NYT10 dataset, maybe you can read their paper to find clues. We just follow the THU convert script and preprocess the pb files mentioned above.
3. We didn't conduct such experiments to show the information leak effect. Since they're under different contexts, maybe the entity pair itself has limited efficacy to identify the relationships. You can have a look at [this paper](https://arxiv.org/abs/2010.01923) to find an empirical intuition.

**Comment by rivercold** [comment]
Thank you for sharing!
